"""add status_code and error_detail to audit logs

Revision ID: 48df87ea8cb9
Revises: 414394ac3975
Create Date: 2026-07-07 11:20:07.383656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48df87ea8cb9'
down_revision: Union[str, Sequence[str], None] = '414394ac3975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=False))
    op.add_column('audit_logs', sa.Column('error_detail', sa.String(), nullable=True))
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_logs', 'detail',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('audit_logs', 'performed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'performed_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'detail',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_logs', 'error_detail')
    op.drop_column('audit_logs', 'status_code')
    # ### end Alembic commands ###
